spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/musicstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mcpe1242666377
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.musicstore.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.musicstore: debug